name: Java CI with Selenium
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest  # Use Windows-based runner
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      - name: Build and Run Java
        run: |
          cd src/BookSearchAutomation  # Navigate to the directory containing the Java file
          javac Automation_test.java
